### ISSUE TITLE
可以给META添加一个前缀，用以辨别

### ISSUE THREAD

**Issue by Aruelius** [Hsury/BiliDrive#1]
参考迅雷的磁力链接
![image](https://user-images.githubusercontent.com/25380989/67539292-3d380980-f714-11e9-80ed-136b4f6dc184.png)

**Comment by Hsury** [comment]
你说加，那就加
![image](https://user-images.githubusercontent.com/26821563/67577285-be25ee00-f772-11e9-9ed4-544f5b93ffcf.png)

**Comment by czp3009** [comment]
那就加到爆炸!
