### ISSUE TITLE
这是b站官方的正式/非正式项目吗？

### ISSUE THREAD

**Issue by afraidjpg** [Hsury/BiliDrive#13]
亦或是内部员工利用手中的服务器全权限进行的开发？或者是破解的b站的防火墙？
么的别的意思..就是好奇..不然这文件万一说没就没了，咱啥也不知道，咱啥也不敢问

**Comment by foxes1998** [comment]
将任意文件分块编码为图片后上传至B站，对该操作逆序即可下载并还原文件

readme.md 不是说了吗

**Comment by Hsury** [comment]
这个项目与B站官方无关，我也不是内鬼XD
