### ISSUE TITLE
对于文件级秒传的支持

### ISSUE THREAD

**Issue by sihuan** [Hsury/BiliDrive#19]
现在上传的时候只是判断某一块是否已经被上传进而实现块级的秒传(跳过上传)
但是如果存在这样的情况：一个文件已经被以n M/块 的分块方式上传，当其他人以 m M/块 的分块方式上传时就不能实现秒传，进而造成资源的浪费。
建议将 Meta 包的 url 设置为文件 sha1 或 文件前 4M sha1 这样在上传的时候就可以判断是否有人上传过该文件。
如无：老老实实上传
如有：直接秒传成功返回 Meta 包地址
       或者
获得 Meta 包，进而解析出 Block 字典，算出之前的上传分块方式，按之前的分块方式进行上传，同样该跳过跳过，查缺补漏（其实鉴于您是在所有Block上传完之后才上传Meta包的，所以不用查缺补漏。。）

**Comment by Hsury** [comment]
哈，其实我在开始写这个项目之前就考虑过可否实现文件级秒传，也想到过这种方案，可惜后来发现B站不支持自定义文件名（目前服务器会对上传的文件计算SHA-1并以其命名文件）。
在这个前提下，要想做到文件级秒传，需要让同一文件产生的META内容具有唯一性。这就要求META中不能引入除待上传文件自身以外的变量，如分块大小与时间戳。并且B站产生的外链也应该是可以在本地推算出来的。分块大小在脚本中也设置了默认值，一般情况下用户也不会去指定。但是外链是由B站服务器生成并返回的，路径结构完全有可能发生变化且无法预测，这里就引入了不确定因素。
因此目前只通过匹配本地记录来实现文件级秒传。
欢迎继续探讨～

**Comment by sihuan** [comment]
我想到一下方案
前提是分块只能是 整数M
设置分块为 nM 的文件，前n-1块按4M上传 从第n块按 nM 上传
这样上传的时候从文件读入4M，测试可否跳过，如果404了就说明没人传过，就按前n-1块4M以后nM上传。如果200了，就继续读入下一个4M知道到第x块404了，以后读入xM上传，不出意外应该全是可跳过的

**Comment by sihuan** [comment]
%s/一下/一个/g

**Comment by sihuan** [comment]
%s/知道/直到/g
我能说我太冷了手抖输错的吗🤣

**Comment by Hsury** [comment]
没太看明白，不过感觉这说的不是文件级秒传的方案吧？感觉还是比不上直接统一分块大小来得简单高效啊= =

**Comment by sihuan** [comment]
我的意思是在一定程度上保留自定义分块功能，同时用开头 n 个 4M 分块来暗示这个文件采用的分块方式
等后来人上传文件的时候，只要判断 第一个 4M是不是被上传过（可跳过）。
可跳过：就可以得知该文件被上传过，就可以继续读入 4m 块，判断是否可跳过，当不可跳过的时候，就可以根据跳过的 4m 块数目来得知前人上传的分块方式。进而算出meta包
不可跳过，说明该文件没被上传过，继续读入并上传若干个4M块后，然后按照设置的大小读入块并上传。
我目前写了一个 go 语言版本的，正在设计文件秒传方式和meta包的内容，还希望和这个项目兼容🤣

**Comment by sihuan** [comment]
就是说通过 文件 前4M sha1来判断是否被上传过，如果上传过后面的步骤就是得出meta包，没有任何上传动作

**Comment by Hsury** [comment]
嗯，我理解了，不过我觉得直接做个文件级秒传的方案会更有价值一些，毕竟性能肯定要比分块秒传优化到极致更好。目前我有一个设计思路：在当前的上传流程结束之后，将该文件前4MB的SHA-1作为索引，再对META URL进行对称加密后上传到一个公共数据库。密钥可使用该文件前4MB的最后n个字节或者什么别的，只要是难以从索引推算出来的东西并约定好算法就行。然后上传前就可以先用这一文件前4MB的SHA-1去公共数据库里查询，如果有记录，就用之前约定好的算法算出密钥，然后解密得到META URL并直接返回。这样在可以实现文件级秒传的同时，即使数据库完全公开透明，也可以确保只有拥有这个文件的用户才能解密得到META URL记录从而访问到文件，保证了隐私安全。

**Comment by Hsury** [comment]
想到一点，还可以设计个二代META URL，携带上述方案中提到的索引与密钥，然后下载时先去公共数据库上拉取实际的META URL，之后就还是原来的流程。这样既能保持兼容性，还能顺便把目前无法做到的文件删除功能也给实现了～

**Comment by sihuan** [comment]
之前想到过引入第三方，但觉得多一个依赖不清真。但是这样看起来的确简单而且干的漂亮。（一个可以删除图片支持自定义命名的图床就可以充当公共数据库吧

**Comment by Hsury** [comment]
> 之前想到过引入第三方，但觉得多一个依赖不清真。但是这样看起来的确简单而且干的漂亮。（一个可以删除图片支持自定义命名的图床就可以充当公共数据库吧

嘿嘿，是这样的

**Comment by sihuan** [comment]
老哥 你好 我做了一个go语言版本
地址 https://github.com/Si-Huan/AcDrive
出于考虑到A站支持自命名图片，我就更改了Meta的格式，没有与之前的兼容
希望你看一下,如果不满意现在的声明或者协议啥的  我都可以再改😂（我也不大懂这些开源协议啥的）

**Comment by Hsury** [comment]
> 老哥 你好 我做了一个go语言版本
> 地址 https://github.com/Si-Huan/AcDrive
> 出于考虑到A站支持自命名图片，我就更改了Meta的格式，没有与之前的兼容
> 希望你看一下,如果不满意现在的声明或者协议啥的 我都可以再改😂（我也不大懂这些开源协议啥的）

巧了，之前我的好朋友 @Aruelius 也在本项目的基础上魔改了个[AcDrive](https://github.com/Hsury/BiliDrive/tree/acfun)
最近在忙别的，协议规范什么的有更好的想法可以先讨论，尽可能做到各个分支互相兼容~

**Comment by sihuan** [comment]
我觉得编码成高1的图片容易被检测，最近稍微了解了一下 BMP 位图的格式，我现在采取的默认方案是默认编码到一个高1080宽1920的每像素占32位的BMP图片里，大概一个图片可以存进8M左右的数据。如果现在 BiliDrive 不能上传的问题在于图片宽度不被接受的话，我就着手编写 python 版本的处理数据为 bmp 的函数，争取解决问题。

**Comment by huqianshan** [comment]
> 我觉得编码成高1的图片容易被检测，最近稍微了解了一下 BMP 位图的格式，我现在采取的默认方案是默认编码到一个高1080宽1920的每像素占32位的BMP图片里，大概一个图片可以存进8M左右的数据。如果现在 BiliDrive 不能上传的问题在于图片宽度不被接受的话，我就着手编写 python 版本的处理数据为 bmp 的函数，争取解决问题。

------
- 刚刚测试了一下，应该是ban了bmp格式图片
![image](https://user-images.githubusercontent.com/23468665/74038191-bd9c2500-49fa-11ea-8c9d-6dfa5369c631.png)
- 去网页端看了一下，好像还真的不能上传bmp格式
![image](https://user-images.githubusercontent.com/23468665/74038288-e3c1c500-49fa-11ea-9d84-83a6b0b28e64.png)
![image](https://user-images.githubusercontent.com/23468665/74038916-eb359e00-49fb-11ea-96d4-c2fa2767db1f.png)


- 不知道up主（repo主嘻嘻）还打算继续维护不。存储格式可能需要大改了，不过关键还是看 β站 愿不愿意留个接口了。模拟登录那块api好像是需要`appkey`的吧，感觉β站可以随时封了。。不知道是不是这样的

**Comment by splinter21** [comment]
直接打死bmp格式了么。。。宁可错杀一千，不能放过一个。。。

投稿封面的图片上传接口有试过吗

**Comment by sihuan** [comment]
投稿上传封面的地方也是只支持 jpg 和 png 呢

**Comment by Hsury** [comment]
> > 我觉得编码成高1的图片容易被检测，最近稍微了解了一下 BMP 位图的格式，我现在采取的默认方案是默认编码到一个高1080宽1920的每像素占32位的BMP图片里，大概一个图片可以存进8M左右的数据。如果现在 BiliDrive 不能上传的问题在于图片宽度不被接受的话，我就着手编写 python 版本的处理数据为 bmp 的函数，争取解决问题。
> 
> * 刚刚测试了一下，应该是ban了bmp格式图片
>   ![image](https://user-images.githubusercontent.com/23468665/74038191-bd9c2500-49fa-11ea-8c9d-6dfa5369c631.png)
> * 去网页端看了一下，好像还真的不能上传bmp格式
>   ![image](https://user-images.githubusercontent.com/23468665/74038288-e3c1c500-49fa-11ea-9d84-83a6b0b28e64.png)
>   ![image](https://user-images.githubusercontent.com/23468665/74038916-eb359e00-49fb-11ea-96d4-c2fa2767db1f.png)
> * 不知道up主（repo主嘻嘻）还打算继续维护不。存储格式可能需要大改了，不过关键还是看 β站 愿不愿意留个接口了。模拟登录那块api好像是需要`appkey`的吧，感觉β站可以随时封了。。不知道是不是这样的

BMP格式看起来是被全面封堵了，然后登录算是相对独立的部分，目前appkey也不太可能封掉，不然官方的客户端也无法登录了。最近在着手重构框架，不再针对B站了hhh

**Comment by snowman** [comment]
use images instead of words
