### ISSUE TITLE
感觉这个项目会造成B站资源的滥用

### ISSUE THREAD

**Issue by zouyonghao** [Hsury/BiliDrive#2]

**Comment by Hsury** [comment]
自述文件中已作出相关提示：
请合理使用本项目，避免对哔哩哔哩的存储与带宽资源造成无意义的浪费

**Comment by wuyuhuihui** [comment]
看不懂，即不能下载b站视频，也不能上传文件。尤其是这个交互界面，看不明白，建议楼主说的详细点

**Comment by Hsury** [comment]
> 看不懂，即不能下载b站视频，也不能上传文件。尤其是这个交互界面，看不明白，建议楼主说的详细点

本项目并非用于解析下载B站投稿视频，另外从你的问题描述中得不到足够多的有用信息，还有主题无关内容请新开Issue。

**Comment by wizardforcel** [comment]
d 站盗链 b 站资源的时候可没见你们抨击过。
