### ISSUE TITLE
编码成视频

### ISSUE THREAD

**Issue by OmmyZhang** [Hsury/BiliDrive#20]
要不要考虑编码成视频上传，这样更隐蔽。
不过视频有审核的问题，可能只有在正常视频里插帧或者在频域里编码什么的。

**Comment by Hsury** [comment]
编码成视频的话，要解决的问题确实还是挺多的= =
比如人工审核机制，可能存在有损的二次压缩，有效数据承载量比较低

**Comment by moeray** [comment]
现在已经被和谐了吗

**Comment by Hsury** [comment]
> 现在已经被和谐了吗

嗯，目前上传文件采用的策略已经被精准和谐了。
