### ISSUE TITLE
登.录.不.了了, 大佬还在维.护吗?

### ISSUE THREAD

**Issue by xn213** [Hsury/BiliDrive#29]
release  第一次登录就提醒`登.录.过/于.频.繁,,,一分钟后重试 继续同样提醒

**Comment by Hsury** [comment]
登录提示“-449 服务繁忙”是正常情况，因为B站调整了相关接口。新的登录实现可以参考我的另一个项目(Bilibili-Toolkit)[https://github.com/Hsury/Bilibili-Toolkit]。

**Comment by Hsury** [comment]
现有版本登录返回“-449 服务繁忙”是正常情况，新的登录实现可以参考我的另一个项目[Bilibili-Toolkit](https://github.com/Hsury/Bilibili-Toolkit)。由于显而易见的原因，本人暂时没有继续更新的计划，但是欢迎PR。
