### ISSUE TITLE
输入账号密码，尝试登陆时卡住

### ISSUE THREAD

**Issue by jzcangshu** [Hsury/BiliDrive#30]
![运行截图](https://p.ananas.chaoxing.com/star3/origin/044191f9bd818917f5ab3ad717382d33.png?rw=1367&rh=765&_fileSize=48033&_orientation=1)
然后等了10分钟左右一直保持这个状态，没有显示任何信息

**Comment by Hsury** [comment]
B站升级了相关接口，会导致先前的登录逻辑陷入死循环
