### ISSUE TITLE
你好厉害呀！有木有协议白皮书（

### ISSUE THREAD

**Issue by simon300000** [Hsury/BiliDrive#4]

**Comment by Hsury** [comment]
没...没有啦

**Comment by simon300000** [comment]
有兴趣做浏览器插件嘛www

**Comment by Hsury** [comment]
所以有大佬来接手吗（

**Comment by simon300000** [comment]
我在思考能不能用JavaScript做浏览器上可以用的版本，但是我不会Python（

**Comment by Hsury** [comment]
理论上应该是可以的，但是巧了我不会JavaScript，逃

**Comment by simon300000** [comment]
那真是太巧了，我好像会点JavaScript→_→

**Comment by Hsury** [comment]
![image](https://user-images.githubusercontent.com/26821563/68544066-0e02e700-03fa-11ea-845e-3c174721b1e5.png)

**Comment by simon300000** [comment]
我发现了，你也是DD，要不要加这个DD程序员群啊（
663606562

**Comment by Hsury** [comment]
我不是，我没有，你不要乱说啊
我单推我家公主殿下
嘿嘿嘿

**Comment by xlzy520** [comment]
@simon300000 浏览器插件我之前做过一个简陋的哔哩哔哩图床上传插件，后来别人推荐作者这个更加骚的

**Comment by snowman** [comment]
jails
