### ISSUE TITLE
违反微软品牌资源条款的可能

### ISSUE THREAD

**Issue by Riajyuu** [Hsury/BiliDrive#6]
![image](https://user-images.githubusercontent.com/16912240/68571935-2416b300-049f-11ea-8bf1-1dea6aa5ba1e.png)

https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general.aspx

建议联系微软法务进行确认

**Comment by Hsury** [comment]
感谢指出！为规避可能存在的风险，已删除图标。
